RHIROS-492 upgrade react-router-dom to v6
RedHatInsights/ros-frontend pull request #170
Opened 2023-02-15 13:06 UTC by r14chandra

2023-07-27 06:26 UTC, PreetiW commented
@r14chandra Can you please rebase this PR so it stays upto date with latest master changes, thanks! 🙌🏻

2023-09-13 11:16 UTC, gkarat commented
Please keep in mind that you also need to bump @redhat-cloud-services/frontend-components to the version at least 3.10.0 and @redhat-cloud-services/frontend-components-utilities to at least 3.6.0.

These versions provide a compatible layer for InventoryTable that will help you avoid regressions while releasing to production disregarding if Inventory is released or not: https://github.com/RedHatInsights/frontend-components/pull/1744.

2023-09-13 11:16 UTC, gkarat requested changes
Please keep in mind that you also need to bump @redhat-cloud-services/frontend-components to the version at least 3.10.0 and @redhat-cloud-services/frontend-components-utilities to at least 3.6.0.

These versions provide a compatible layer for InventoryTable that will help you avoid regressions while releasing to production disregarding if Inventory is released or not: https://github.com/RedHatInsights/frontend-components/pull/1744.

2023-09-14 08:51 UTC, r14chandra commented
/restest

2023-09-15 11:52 UTC, gkarat approved these changes
Looks good to me! Tested locally and couldn't spot any issues. Thanks @r14chandra

2023-09-15 11:52 UTC, gkarat commented on package.json
I hope so many dependencies upgrades within this PR won't cause any bugs. I would limit the upgrades only to those that are required at the moment (for this PR).

2023-09-15 12:06 UTC, r14chandra commented on package.json
Thanks for the review @gkarat. It was added by Martin. I will revert the dependencies upgrades.

2023-09-15 12:25 UTC, PreetiW commented
/retest

2023-09-18 06:47 UTC, PreetiW commented
@r14chandra can you please check why the tests are failing?

2023-09-18 07:12 UTC, r14chandra commented
> @r14chandra can you please check why the tests are failing?

Tests are not failing, it is failing on the deployment job.  
I have asked this on the channel.

2023-09-20 07:57 UTC, Hyperkid123 commented
@r14chandra you are missing a babel dependency. Run `npm i --save-dev @babel/runtime` and the issue will go away.

2023-09-28 05:46 UTC, PreetiW commented
@r14chandra can you please rebase this branch?

2023-10-25 10:01 UTC, yash2189 commented
/retest

2023-10-26 10:25 UTC, yash2189 commented
Tested this on EE and executed iqe smoke tests for ros plugin. detailed observations are added on Jira

2023-10-26 10:40 UTC, merged