update docs versions for Insights, Console, Cost & Subscriptions
RedHatInsights/ros-frontend pull request #175
Opened 2023-02-21 18:04 UTC by ryandeussing

## PR Title :boom:

Where links to Insights, Console, Cost & Subscriptions docs exist, this PR updates the url to the 2023 version
Suggested formats: 

1. Fixes/Refs #RHIROS-XXX - Title
2. RHIROS-XXX Title 

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here.

## Documentation requires update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2023-03-02 10:26 UTC, PreetiW commented
/retest

2023-03-02 11:08 UTC, PreetiW requested changes
Thank you for the PR @ryandeussing 🙌🏻 
I see the [jobs are failing](https://ci.int.devshift.net/job/RedHatInsights-ros-frontend-pr-check/125/console), can you please run the lint `npm run lint` on the PR and fix the issues using `lint:js:fix`? Let me know if you have any questions! 💯

2023-03-07 20:12 UTC, kgaikwad requested changes

2023-03-07 20:12 UTC, kgaikwad commented on src/constants.js
> +];
```suggestion
export const MONTHS = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
];
```

2023-03-07 20:12 UTC, kgaikwad commented on src/constants.js
> +  },
```suggestion
    {
        key: 'display_name',
        title: 'Name',
        modalTitle: 'Name',
        renderFunc: (data, id, item) => systemName(data, id, item),
        isChecked: true,
        isDisabled: true,
        isShownByDefault: true
    },
    {
        key: 'os',
        title: (
            <Tooltip content={<span>Operating system</span>}>
                <span>OS</span>
            </Tooltip>
        ),
        modalTitle: 'Operating system',
        dataLabel: 'Operating system',
        renderFunc: (data) => displayOS(data),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true
    },
    {
        key: 'performance_utilization.cpu',
        title: 'CPU utilization',
        modalTitle: 'CPU utilization',
        renderFunc: (data, id, item) => scoreProgress(data, id, item),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true
    },
    {
        key: 'performance_utilization.memory',
        title: 'Memory utilization',
        modalTitle: 'Memory utilization',
        renderFunc: (data, id, item) => scoreProgress(data, id, item),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true
    },
    {
        key: 'performance_utilization.max_io',
        title: (
            <Tooltip content={<span>IOPS</span>}>
                <span>I/O utilization</span>
            </Tooltip>
        ),
        modalTitle: 'I/O utilization',
        dataLabel: 'I/O utilization',
        renderFunc: (data, id, item) => diskUsageData(data, id, item),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true
    },
    {
        key: 'number_of_suggestions',
        title: 'Suggestions',
        modalTitle: 'Suggestions',
        renderFunc: (data, id, item) => recommendations(data, id, item),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true
    },
    {
        key: 'state',
        title: 'State',
        modalTitle: 'State',
        renderFunc: (data) => displayState(data),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true
    },
    {
        key: 'report_date',
        title: 'Last reported',
        modalTitle: 'Last reported',
        renderFunc: (data) => displayLastReported(data),
        isChecked: true,
        isDisabled: false,
        isShownByDefault: true,
        transforms: [nowrap],
        cellTransforms: [nowrap]
    }
```

2023-03-07 20:12 UTC, kgaikwad commented on src/constants.js
> +  },
```suggestion
     state: {
        label: 'State',
        type: 'checkbox',
        filterValues: {
            items: [
                {
                    label: 'Idling',
                    value: 'Idling'
                },
                {
                    label: 'Optimized',
                    value: 'Optimized'
                },
                {
                    label: 'Oversized',
                    value: 'Oversized'
                },
                {
                    label: 'Under pressure',
                    value: 'Under pressure'
                },
                {
                    label: 'Undersized',
                    value: 'Undersized'
                },
                {
                    label: 'Waiting for data',
                    value: 'Waiting for data'
                }
            ]
        }
    }
```

2023-03-07 20:12 UTC, kgaikwad commented on src/constants.js
> +  'https://access.redhat.com/documentation/en-us/red_hat_insights/2023/html/assessing_and_monitoring_rhel_resource_optimization_with_insights_for_red_hat_enterprise_linux/con-ros-overview_ros-overvie
```suggestion
export const GETTING_STARTED_URL =  'https://access.redhat.com/documentation/en-us/red_hat_insights/2023/html/assessing_and_monitoring_rhel_resource_optimization_with_insights_for_red_hat_enterprise_linux/con-ros-overview_ros-overview';
```

2023-03-07 20:12 UTC, kgaikwad commented on src/constants.js
> +  systemName,
```suggestion
    displayState,
    recommendations,
    scoreProgress,
    systemName
```

2023-03-07 20:12 UTC, kgaikwad commented on src/constants.js
> +  displayOS,
```suggestion
    diskUsageData,
    displayLastReported,
    displayOS
```

2023-03-07 20:18 UTC, kgaikwad commented on src/constants.js
>          filterValues: {
```suggestion
    state: {
        label: 'State',
        type: 'checkbox',
        filterValues: {
```

2023-03-07 20:20 UTC, kgaikwad commented on src/constants.js
> +export const GETTING_STARTED_URL =  'https://access.redhat.com/documentation/en-us/red_hat_insights/2023/html/assessing_and_monitoring_rhel_resource_optimization_with_insights_for_red_hat_enterprise_
```suggestion
export const GETTING_STARTED_URL = 'https://access.redhat.com/documentation/en-us/red_hat_insights/2023/html/assessing_and_monitoring_rhel_resource_optimization_with_insights_for_red_hat_enterprise_linux/con-ros-overview_ros-overview';
```

2023-03-07 20:24 UTC, merged