feat(RHIN-830): Add ZeroState to ROS
RedHatInsights/ros-frontend pull request #201
Opened 2023-05-02 17:56 UTC by adonispuente

As in accordance to these mocks, this PR adds zero state to patch,  https://docs.google.com/document/d/1FGuzbL2jyRmn_coYD5Z_o3d0MhOf1vQDT46NQvsfPyA/edit#heading=h.1hvxoje16w3i  https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/qbe9Ol2#Inspect   https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/prototype/a/AEF47CA9-8F00-40FC-B39B-3B989D3F83FD   To test, sign into an account with 0 systems connected 

2023-05-04 19:12 UTC, PreetiW requested changes
Thank you for creating the PR @adonispuente 🙌🏻 
I have added the details from my side, let me know what you think! 💯

2023-05-04 20:06 UTC, PreetiW commented on src/Routes.js
> +                /> :
As per out [discussion over slack ](https://redhat-internal.slack.com/archives/C01C1GVT3TP/p1683227722535999?thread_ts=1683202174.312729&cid=C01C1GVT3TP)I have pushed the changes to the PR 🙌🏻

2023-05-05 06:36 UTC, PreetiW commented
/retest

2023-05-05 08:57 UTC, r14chandra requested changes
Looks good to me 👍🏻 
@PreetiW Added one minor suggestion. Otherwise, the PR is good to go.
Tested it on Preview env, working fine. The app breaks on Stage env which is a known issue.

2023-05-06 14:26 UTC, PreetiW commented
@r14chandra the issue is fixed in the stage env and it is working fine now in stage. Can I go ahead with merging the PR?

2023-05-06 14:30 UTC, r14chandra approved these changes
Thanks @PreetiW. The PR looks good. 👍🏻

2023-05-06 14:33 UTC, merged