RHIENG-9113 fixed jest config and added unit tests
RedHatInsights/ros-frontend pull request #331
Opened 2024-04-23 07:25 UTC by PreetiW

## PR Title :boom:

Please title this PR with a summary of the change, along with the JIRA card number.

Suggested formats: 

1. Fixes/Refs #RHIROS-XXX - Title
2. RHIROS-XXX Title 

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here.

## Documentation requires update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2024-05-16 11:08 UTC, r14chandra requested changes
Thanks for the PR, @PreetiW! I have requested some changes. Have a look.

2024-06-14 06:46 UTC, PreetiW commented on src/Components/SystemDetail/RecommendationsTable.test.js
> +// test.todo('RecommendationsTable component tests');
done, will push the changes in the next commit.

2024-06-14 06:48 UTC, PreetiW commented on src/Components/NoEntitiesFound/NoEntitiesFound.test.js
> +describe('NoEntitiesFound tests', () => {
@r14chandra I like to start the test with `describe` to specify the main work and then use `it` for different test cases and hence I used the same here. For now I am resolving the comment, feel free to open it if any changes needed 🙌🏻

2024-06-14 06:49 UTC, PreetiW commented on src/Components/RecommendationRating/RecommendationRating.test.js
> +    it('expect to render when no feedback submitted', () => {
@r14chandra done, will push the changes in next commit. 💯

2024-06-14 06:52 UTC, PreetiW commented on src/Components/RecommendationRating/RecommendationRating.test.js
> +        const propValues = {
@r14chandra you are correct but as the code is very small and `propValues` are different for each case I feel its okay to keep it like this. For now resolving this comment, feel free to open if needed.

2024-06-14 06:53 UTC, PreetiW commented on src/Components/RecommendationRating/RecommendationRating.test.js
> +    it('expect to render with positive feedback', () => {
done, will push the changes in the next commit. 💯

2024-06-14 06:53 UTC, PreetiW commented on src/Components/RecommendationRating/RecommendationRating.test.js
> +    it('expect to render with negative feedback', () => {
done, will push the changes in the next commit. 💯

2024-06-14 06:54 UTC, PreetiW commented on src/Components/Reports/Common/SystemsTablePage.test.js
> +describe('Systems Table Page Component', () => {
done, will push the changes in the next commit. 💯

2024-06-14 06:54 UTC, PreetiW commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +describe('Systems First Page Component', () => {
done, will push the changes in the next commit. 💯

2024-06-14 06:57 UTC, PreetiW commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +    it('should matches snapshot for systems first page and renders correctly with 1 system', () => {
@r14chandra Done, will push the changes in the next commit. 💯

2024-06-14 06:58 UTC, PreetiW commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +    Section: jest.fn(({ children, ...props }) => <div {...props}>{children}</div>),
@r14chandra is it okay to keep the above code? For now I am resolving the comment. Feel free to open it if it is necessary to change the mock implementation. Thanks!

2024-06-14 11:45 UTC, r14chandra commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +    Section: jest.fn(({ children, ...props }) => <div {...props}>{children}</div>),
IMO, this code is unclear and complex. Please feel free to update the code as suggested to make it modular.

2024-06-14 11:47 UTC, r14chandra requested changes
Overall the PR looks good now. Just suggested one change.

2024-06-14 11:47 UTC, r14chandra commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +    Section: jest.fn(({ children, ...props }) => <div {...props}>{children}</div>),
IMO, this code is unclear and complex. Please feel free to update the code as suggested to make it modular.

2024-06-15 17:13 UTC, PreetiW commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +    Section: jest.fn(({ children, ...props }) => <div {...props}>{children}</div>),
Hello @r14chandra, can you please share what is unclear/complex in the above code? As I would like to keep it as to be able to generate below snapshot. Let me know!

![image](https://github.com/RedHatInsights/ros-frontend/assets/5928530/77f5350e-18af-4522-8c5f-7c004ff18825)

2024-06-18 06:09 UTC, r14chandra commented on src/Components/Reports/Common/SystemsFirstPage.test.js
> +    Section: jest.fn(({ children, ...props }) => <div {...props}>{children}</div>),
I missed it!

2024-06-18 06:09 UTC, r14chandra approved these changes
lgtm!

2024-06-18 06:10 UTC, merged