fix(RHINENG-9387): update page titles
RedHatInsights/ros-frontend pull request #336
Opened 2024-05-09 14:28 UTC by mkholjuraev

## PR Title :boom:

This updates the page titles according to this [ticket](https://issues.redhat.com/browse/RHINENG-9387) and [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)

Suggested formats: 

1. Fixes/Refs #RHIROS-XXX - Title
2. RHIROS-XXX Title 

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here.

## Documentation requires update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2024-05-10 11:21 UTC, r14chandra commented
/retest

2024-05-10 11:22 UTC, r14chandra commented
\retest

2024-05-13 12:55 UTC, PreetiW commented
/retest

2024-05-15 09:45 UTC, gkarat commented
@mkholjuraev, @PreetiW, there is a linter failing on both ci.int and Travis. The issue is really weird and seems to have started happening with this PR. Though I don't really understand where this `range` comes from:
```
TypeError: Cannot read properties of null (reading 'range')
Occurred while linting /home/travis/build/RedHatInsights/ros-frontend/src/Routes/RosSystemDetail/RosSystemDetail.js:1
```

2024-05-15 14:28 UTC, mkholjuraev commented
@PreetiW @gkarat This maybe due to the old unsupported version of babel-eslint package. @PreetiW I am wondering if you are going to migrate away from this package?

2024-05-16 10:20 UTC, gkarat commented
Can we still merge the PR without waiting for this upgrade? The PR changes are minor and only touch the page titles.

2024-05-16 13:01 UTC, PreetiW commented on src/Routes/RosSystemDetail/RosSystemDetail.js
> +            chrome?.updateDocumentTitle(`${displayName} - Resource Optimization - Business`);
@mkholjuraev for now can you please put the title in a variable and use it? for eg:
`const detailPageTitle = `${displayName} - Resource Optimization - Business`;
 chrome?.updateDocumentTitle(detailPageTitle);`

I checked the lint is not complaining with this. I will look into the lint issue later around why it gives error with above code. 
Thank you!

2024-05-16 13:02 UTC, PreetiW requested changes
Thank you for the PR @mkholjuraev. I have requested a minor change, let me know once its done and I will go ahead and merge the PR. 🙌🏻

2024-05-17 03:28 UTC, PreetiW approved these changes
@mkholjuraev Thank you for making the changes. Merging it 💯

2024-05-17 03:28 UTC, merged