RHIROS #181 - Add titles to expanded recommendations
RedHatInsights/ros-frontend pull request #45
Opened 2021-07-06 13:24 UTC by apuntamb

![recomm_title](https://user-images.githubusercontent.com/9948256/124607560-98c80d80-de8b-11eb-8d05-cece7aba335f.png)

2021-07-09 09:23 UTC, kgaikwad requested changes
@apuntamb, added inline observations.

+ adding @terezanovotna into loop for UX review.

2021-07-09 09:23 UTC, kgaikwad commented on src/Components/SystemDetail/RecommendationsTable.js
>              </Text>
Attached screenshot vs mockup [page](https://marvelapp.com/prototype/geig8bh/screen/80186730):
- Blank space between two paragraphs is missing.

2021-07-09 09:23 UTC, kgaikwad commented on src/Components/SystemDetail/RecommendationsTable.js
> +                <Text style={{ fontWeight: 'bold' }}>Recommendation</Text>
Instead of adding inline style, could please make use of either strong tag or CSS class?

2021-07-12 07:10 UTC, apuntamb commented
@kgaikwad Tried using `<strong>` and `<br>`. Is this a good approach to addressing your comment? Thoughts?

2021-07-12 11:17 UTC, kgaikwad requested changes
@apuntamb, added few inline changes.

2021-07-13 09:36 UTC, kgaikwad approved these changes
LGTM :+1:

2021-07-13 09:43 UTC, terezanovotna commented
Looks great! My only thing was to add a space above Recommendation but I see it is already fixed :)

2021-07-13 09:53 UTC, kgaikwad commented
Thank you @terezanovotna & @apuntamb for the change!
Merging this pull-request

2021-07-13 09:53 UTC, merged