handling no data UI for utilization  bars
RedHatInsights/ros-frontend pull request #68
Opened 2021-11-09 12:34 UTC by PreetiW

Card:
https://issues.redhat.com/browse/RHIROS-382

![image](https://user-images.githubusercontent.com/5928530/140925052-5cdf218e-1b3d-404e-8ad6-0e573cba5803.png)

2021-11-09 14:19 UTC, kgaikwad requested changes
Thank you @PreetiW! 
Added one inline observation, please let me know your thoughts.

2021-11-09 14:19 UTC, kgaikwad commented on src/store/entitiesReducer.js
> +                    <span>{ NO_DATA_VALUE }</span>
@PreetiW - It seems that with `recommendations` CSS class [here](https://github.com/RedHatInsights/ros-frontend/blob/main/src/Routes/RosPage/ros-page.scss#L25), it adjusts the left padding.
One observation: with this change, when there will be multiple records, vertical alignment for column `Suggestions` will not be same for rows.

2021-11-09 18:13 UTC, kgaikwad approved these changes

2021-11-09 18:18 UTC, merged

2021-11-09 18:20 UTC, kgaikwad commented
Thanks @PreetiW for quick updates.
Just a small suggestion - if JIRA ticket exists for a change request, it would be good to include ticket number in git commit message for a future reference.

2021-11-10 06:50 UTC, PreetiW commented
> Thanks @PreetiW for quick updates. Just a small suggestion - if JIRA ticket exists for a change request, it would be good to include ticket number in git commit message for a future reference.

Thank you for the reminder @kgaikwad as I forgot to do it for this PR. I will surely do it in the future.